name: CI

on:
  push:
    branches:
      - main

jobs:
  standard-checks:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.15.1"

      - name: Source nvm
        run: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install packages
        run: npm ci

      - name: Run ESlint
        run: npm run lint

      #- name: Run Tests
      #  run: npm test

      - name: Build Angular App
        run: ng build --configuration production

      - name: Bundle and Output
        run: npm run build
